Repository columnflow/columnflow, pull requests merged in 2022-07, with the labels that each got.

#59 Add and use SelectorStepsMixin
  ap/tasks/framework/mixins.py
  ap/tasks/histograms.py
  ap/tasks/plotting.py
  ap/tasks/production.py
  ap/tasks/reduction.py
  ap/tasks/selection.py
Labels: enhancement, medium-priority

#60 Preserve order in object lookup via patterns.
  ap/tasks/framework/base.py
  ap/tasks/framework/mixins.py
Labels: medium-priority, fix

#63 Complex route lookups.
  README.rst
  ap/columnar_util.py
  ap/config/variables.py
  ap/ml/__init__.py
  ap/tasks/cutflow.py
  ap/tasks/histograms.py
  ap/util.py
Labels: enhancement, medium-priority

#66 Add producer identifying gen top decay chains
  ap/config/campaign_2018.py
  ap/production/gen_top_decay.py
  ap/selection/test.py
Labels: enhancement, medium-priority

#69 Features/unit tests
  .github/workflows/lint_and_test.yaml
  bin/ap_create_venv
  bin/ap_make_venv_relocateable
  requirements_dev.txt
  sandboxes/dev.txt
  sandboxes/venv_columnar_dev.sh
  sandboxes/venv_docs_dev.sh
  sandboxes/venv_ml_tf_dev.sh
  tests/__init__.py
  tests/run_coverage
  tests/run_docs
  tests/run_test
  tests/run_tests
  tests/test_columnar_util.py
Labels: testing, high-priority

#67 Externalize plotting
  ap/plotting/plotter.py
  ap/plotting/variables.py
  ap/tasks/cutflow.py
  ap/tasks/plotting.py
  ap/util.py
Labels: enhancement, medium-priority

#71 Store and apply event weight sums per process.
  ap/production/normalization.py
  ap/selection/test.py
Labels: enhancement, low-priority

#72 Allow dynamic plot functions.
  .github/workflows/lint_and_test.yaml
  ap/plotting/__init__.py
  ap/plotting/plotter.py
  ap/plotting/variables.py
  ap/tasks/framework/mixins.py
  ap/tasks/plotting.py
  codecov.yml
Labels: enhancement, medium-priority

#74 Adapt plots to mpl version in venv_columnar.
  ap/config/analysis_st.py
  ap/plotting/plotter.py
  ap/plotting/variables.py
  ap/tasks/plotting.py
Labels: enhancement, medium-priority

#75 First set of core generalizations
  ap/tasks/calibration.py
  ap/tasks/cutflow.py
  ap/tasks/external.py
  ap/tasks/framework/base.py
  ap/tasks/framework/mixins.py
  ap/tasks/framework/remote.py
  ap/tasks/histograms.py
  ap/tasks/inference.py
  ap/tasks/ml.py
  ap/tasks/plotting.py
  ap/tasks/production.py
  ap/tasks/reduction.py
  ap/tasks/selection.py
  law.cfg
Labels: enhancement, high-priority
