Repository columnflow/columnflow, pull requests merged in 2022-08, with the labels that each got.

#83 Feature/tests to be approved
  ap/columnar_util.py
  tests/test_columnar_util.py
Labels: testing

#92 Add mc_weight producer, favor over lhe weight
  columnflow/example_config/analysis_st.py
  columnflow/production/mc_weight.py
  columnflow/production/normalization.py
  columnflow/selection/example.py
  columnflow/tasks/cutflow.py
Labels: enhancement, high-priority

#93 Make all array operations return views.
  columnflow/calibration/example.py
  columnflow/calibration/jets.py
  columnflow/columnar_util.py
  columnflow/ml/__init__.py
  columnflow/ml/example.py
  columnflow/production/categories.py
  columnflow/production/example.py
  columnflow/production/gen_top_decay.py
  columnflow/production/normalization.py
  columnflow/production/pileup.py
  columnflow/production/processes.py
  columnflow/production/seeds.py
  columnflow/selection/example.py
  columnflow/tasks/calibration.py
  columnflow/tasks/cutflow.py
  columnflow/tasks/histograms.py
  columnflow/tasks/ml.py
  columnflow/tasks/production.py
  columnflow/tasks/reduction.py
  columnflow/tasks/selection.py
  tests/test_columnar_util.py
Labels: bug, high-priority
