Repository columnflow/columnflow, pull requests merged in 2022-12, with the labels that each got.

#121 Support masks in electron/muon weight producers.
  columnflow/production/btag.py
  columnflow/production/electron.py
  columnflow/production/muon.py
Labels: enhancement, high-priority

#120 Rotate cutflow bin labels to prevent overlap.
  columnflow/plotting/example.py
Labels: medium-priority, plotting

#124 Apply JEC/JER smearing via correctionlib
  columnflow/calibration/jets.py
  columnflow/calibration/jets_coffea.py
  columnflow/calibration/util.py
Labels: enhancement, high-priority

#131 Check for non-finite numbers before writing.
  columnflow/tasks/calibration.py
  columnflow/tasks/framework/mixins.py
  columnflow/tasks/ml.py
  columnflow/tasks/production.py
  columnflow/tasks/selection.py
  law.cfg
Labels: enhancement, medium-priority

#130 Generalize plot function handling.
  columnflow/columnar_util.py
  columnflow/plotting/plot2d.py
  columnflow/tasks/cutflow.py
  columnflow/tasks/framework/parameters.py
  columnflow/tasks/framework/plotting.py
  columnflow/tasks/plotting.py
Labels: enhancement, medium-priority

#133 Add CoalesceColumns task.
  columnflow/tasks/reduction.py
  columnflow/tasks/union.py
  law.cfg
Labels: enhancement, medium-priority
