Repository columnflow/columnflow, pull requests merged in 2022-06, with the labels that each got.

#7 Majoras mask staging
  ap/__init__.py
  ap/config/analysis_st.py
  ap/order_util.py
  ap/selection/test.py
  ap/tasks/__init__.py
  ap/tasks/framework/__init__.py
  ap/tasks/framework/remote.py
  ap/tasks/histograms.py
  ap/tasks/plotting.py
  ap/tasks/selection.py
Labels: enhancement

#27 Add BundleExternalFiles task to external.py.
  ap/config/analysis_st.py
  ap/tasks/external.py
  ap/tasks/framework/base.py
Labels: enhancement, high-priority

#29 Add task to calculate PU weights
  ap/config/analysis_st.py
  ap/tasks/external.py
  ap/tasks/framework/base.py
Labels: enhancement, high-priority

#41 Fix ci.
  setup.sh
Labels: bug, high-priority

#37 Perform cleaning of objects on arbitrary metric, e.g. delta R
  ap/selection/__init__.py
  ap/selection/test.py
Labels: bug, high-priority

#45 Allow selection to produce columns, closes #44.
  ap/selection/__init__.py
  ap/selection/test.py
  ap/tasks/histograms.py
  ap/tasks/reduction.py
  ap/tasks/selection.py
  ap/util.py
Labels: enhancement, high-priority

#46 Automate event weights.
  ap/columnar_util.py
  ap/config/analysis_st.py
  ap/config/campaign_2018.py
  ap/production/features.py
  ap/production/normalization.py
  ap/production/pileup.py
  ap/production/test.py
  ap/production/weights.py
  ap/selection/test.py
  ap/tasks/external.py
  ap/tasks/histograms.py
  law.cfg
Labels: enhancement, medium-priority

#48 Add conditional top pt weight
  ap/config/analysis_st.py
  ap/config/campaign_2018.py
  ap/production/weights.py
  ap/tasks/framework/base.py
Labels: enhancement, medium-priority

#51 Add explicit array function flags
  ap/columnar_util.py
Labels: enhancement, medium-priority

#54 Assume all tree array functions to work in-place
  ap/calibration/seeds.py
  ap/calibration/test.py
  ap/columnar_util.py
  ap/production/features.py
  ap/production/normalization.py
  ap/production/pileup.py
  ap/production/processes.py
  ap/production/weights.py
  ap/selection/__init__.py
  ap/selection/test.py
  ap/tasks/calibration.py
  ap/tasks/framework/base.py
  ap/tasks/framework/mixins.py
  ap/tasks/histograms.py
  ap/tasks/plotting.py
  ap/tasks/production.py
  ap/tasks/reduction.py
  ap/tasks/selection.py
  law.cfg
Labels: enhancement, medium-priority
