Repository columnflow/columnflow, pull requests merged in 2023-03, with the labels that each got.

#205 Allow diverging training phase space
  README.md
  columnflow/ml/__init__.py
  columnflow/tasks/ml.py
Labels: enhancement, medium-priority, ML

#209 Fix empty setup mode for remote jobs.
  sandboxes/_setup_venv.sh
Labels: high-priority, fix

#210 Update default chunk size
  analysis_templates/cms_minimal/law.cfg
  law.cfg
Labels: enhancement, medium-priority

#212 Ensure unique sandbox install paths.
  analysis_templates/cms_minimal/sandboxes/example.sh
  analysis_templates/cms_minimal/sandboxes/example_dev.sh
  bin/cf_sandbox_file_hash
  bin/cf_sandbox_file_hash.py
  columnflow/tasks/framework/remote.py
  columnflow/util.py
  docs/requirements.txt
  sandboxes/_setup_cmssw.sh
  sandboxes/_setup_venv.sh
  sandboxes/cf_dev.sh
  sandboxes/cf_prod.sh
  sandboxes/cmssw_default.sh
  sandboxes/columnar.txt
  sandboxes/ml_tf.txt
  sandboxes/venv_columnar.sh
  sandboxes/venv_columnar_dev.sh
  sandboxes/venv_docs_dev.sh
  sandboxes/venv_ml_tf.sh
  sandboxes/venv_ml_tf_dev.sh
  setup.sh
Labels: high-priority, fix

#218 Speed up gen top decay producer.
  columnflow/calibration/__init__.py
  columnflow/production/__init__.py
  columnflow/production/cms/gen_top_decay.py
  columnflow/selection/__init__.py
Labels: enhancement, medium-priority

#219 Implementation of CreateYieldTable task
  columnflow/tasks/yields.py
  columnflow/util.py
  law.cfg
  requirements_prod.txt
Labels: enhancement, medium-priority
