Repository columnflow/columnflow, pull requests merged in 2023-07, with the labels that each got.

#257 Allow custom cms label postfixes in plots.
  columnflow/plotting/plot_all.py
  columnflow/tasks/framework/plotting.py
Labels: enhancement, priority-medium, plotting

#258 Propagate local and global shift correctly to CSPs
  columnflow/production/cms/btag.py
  columnflow/tasks/framework/base.py
Labels: enhancement, priority-medium

#260 Skip calibration outputs and requirements dynamically.
  columnflow/tasks/calibration.py
  columnflow/tasks/histograms.py
  columnflow/tasks/ml.py
  columnflow/tasks/production.py
  columnflow/tasks/reduction.py
  columnflow/tasks/selection.py
  columnflow/tasks/union.py
Labels: enhancement, priority-medium

#261 Rename cf_prod venv to cf, improve dev_sandbox
  analysis_templates/cms_minimal/__cf_module_name__/config/analysis___cf_short_name_lc__.py
  bin/cf_sandbox_file_hash.py
  columnflow/util.py
  sandboxes/cf.sh
  setup.sh
Labels: enhancement, priority-medium

#259 Allow customizing default columnar sandbox
  analysis_templates/cms_minimal/__cf_module_name__/config/analysis___cf_short_name_lc__.py
  columnflow/tasks/calibration.py
  columnflow/tasks/cms/inference.py
  columnflow/tasks/cutflow.py
  columnflow/tasks/histograms.py
  columnflow/tasks/ml.py
  columnflow/tasks/plotting.py
  columnflow/tasks/production.py
  columnflow/tasks/reduction.py
  columnflow/tasks/selection.py
  columnflow/tasks/union.py
  columnflow/tasks/yields.py
  law.cfg
Labels: enhancement, priority-medium

#262 Add skip_fn to create_category_combinations.
  columnflow/config_util.py
Labels: enhancement, priority-medium

#255 Add shift filters to csp decorators
  columnflow/calibration/__init__.py
  columnflow/config_util.py
  columnflow/production/__init__.py
  columnflow/selection/__init__.py
Labels: enhancement, priority-medium

#254 Add selection utils.
  analysis_templates/cms_minimal/__cf_module_name__/selection/example.py
  columnflow/selection/util.py
  columnflow/tasks/reduction.py
Labels: enhancement, priority-medium

#240 Check that used/produced columns exist
  columnflow/calibration/cms/jets.py
  columnflow/calibration/cms/jets_coffea.py
  columnflow/columnar_util.py
  columnflow/production/cms/gen_top_decay.py
  columnflow/production/cms/mc_weight.py
  columnflow/production/cms/muon.py
  columnflow/production/cms/scale.py
  columnflow/production/cms/seeds.py
  columnflow/selection/cms/met_filters.py
Labels: enhancement, priority-medium

#253 Add generic increment_stats selector.
  analysis_templates/cms_minimal/__cf_module_name__/selection/example.py
  columnflow/selection/stats.py
Labels: enhancement, priority-medium

#264 Improve increment_stats.
  analysis_templates/cms_minimal/__cf_module_name__/selection/example.py
  columnflow/columnar_util.py
  columnflow/production/cms/seeds.py
  columnflow/selection/stats.py
  columnflow/tasks/selection.py
Labels: enhancement, priority-medium

#251 Updated version of documentation
  columnflow/calibration/__init__.py
  columnflow/calibration/cms/__init__.py
  columnflow/calibration/cms/jets.py
  columnflow/calibration/cms/jets_coffea.py
  columnflow/calibration/cms/met.py
  columnflow/calibration/util.py
  columnflow/columnar_util.py
  columnflow/production/__init__.py
  columnflow/production/util.py
  columnflow/selection/__init__.py
  columnflow/selection/cms/json_filter.py
  columnflow/selection/cms/met_filters.py
  columnflow/selection/matching.py
  columnflow/tasks/calibration.py
  columnflow/tasks/external.py
  columnflow/tasks/framework/base.py
  columnflow/tasks/framework/mixins.py
  docs/api/calibration/cms.rst
  docs/api/calibration/index.rst
  docs/api/calibration/jets.rst
  docs/api/calibration/jets_coffea.rst
  docs/api/calibration/met.rst
  docs/api/calibration/util.rst
  docs/api/columnar_util.rst
  docs/api/production/index.rst
  docs/api/production/util.rst
  docs/api/selection/cms.rst
  docs/api/selection/index.rst
  docs/api/selection/json_filter.rst
  docs/api/selection/matching.rst
  docs/api/selection/met_filters.rst
  docs/api/tasks/calibration.rst
  docs/api/tasks/cms.rst
  docs/api/tasks/external.rst
  docs/api/tasks/framework/base.rst
  docs/api/tasks/framework/index.rst
  docs/api/tasks/framework/mixins.rst
  docs/api/tasks/index.rst
  docs/api/tasks/introduction.md
  docs/api/tasks/reduction.rst
  docs/api/tasks/selection.rst
  docs/api/util.rst
  docs/conf.py
  docs/law.cfg
  docs/requirements.txt
Labels: documentation, enhancement, priority-high

#266 allow setting default csp via function
  columnflow/tasks/framework/base.py
  columnflow/tasks/framework/mixins.py
Labels: enhancement, priority-medium

#265 Read inputs for lambda-valued variable expressions.
  columnflow/tasks/cutflow.py
  columnflow/tasks/histograms.py
Labels: enhancement, priority-medium

#270 Add process scale attribute to inference model
  columnflow/inference/__init__.py
  columnflow/inference/cms/datacard.py
Labels: enhancement, priority-medium

#272 Improve version lookup in version map
  analysis_templates/cms_minimal/__cf_module_name__/config/analysis___cf_short_name_lc__.py
  columnflow/tasks/framework/base.py
Labels: enhancement, priority-medium

#269 Add DeferredColumn.
  columnflow/columnar_util.py
Labels: enhancement, priority-medium

#273 Fix hiding of error bars.
  columnflow/plotting/plot_all.py
  columnflow/plotting/plot_functions_1d.py
  columnflow/plotting/plot_util.py
Labels: priority-medium, fix, plotting

#277 Fix ratio plotting for MC stack with empty bins
  columnflow/plotting/plot_all.py
Labels: bug, priority-high
