Repository columnflow/columnflow, pull requests merged in 2023-05, with the labels that each got.

#238 Handle negative and missing values in 2d plots
  columnflow/plotting/plot_functions_2d.py
  columnflow/plotting/plot_util.py
  columnflow/tasks/framework/plotting.py
Labels: enhancement, priority-medium, fix, plotting

#243 Uncomment uncertainty combination.
  columnflow/tasks/yields.py
Labels: priority-low, fix

#233 Feature/allow histogramming jagged variables
  analysis_templates/cms_minimal/__cf_module_name__/config/analysis___cf_short_name_lc__.py
  columnflow/tasks/cutflow.py
  columnflow/tasks/histograms.py
Labels: priority-medium, plotting

#245 Feature/producers groups
  columnflow/tasks/framework/base.py
  columnflow/tasks/framework/mixins.py
Labels: enhancement, priority-medium

#248 Catch unkown process ids.
  analysis_templates/cms_minimal/__cf_module_name__/config/analysis___cf_short_name_lc__.py
  columnflow/config_util.py
  columnflow/production/normalization.py
Labels: enhancement, priority-medium
