Repository columnflow/columnflow, pull requests merged in 2023-11, with the labels that each got.

#339 Use dict_encoding for selection results.
  columnflow/tasks/framework/base.py
  columnflow/tasks/selection.py
Labels: enhancement, priority-medium

#340 Change SelectionResult structure, add bool checks.
  analysis_templates/cms_minimal/__cf_module_name__/selection/example.py
  columnflow/selection/__init__.py
  columnflow/selection/stats.py
  columnflow/tasks/selection.py
Labels: enhancement, priority-medium

#342 Ensure Python 3.7 compatibility.
  columnflow/plotting/plot_util.py
  columnflow/production/cms/pdf.py
  columnflow/tasks/framework/base.py
  columnflow/tasks/framework/mixins.py
  setup.py
Labels: enhancement, priority-medium

#345 Refactor chunked parquet reading
  columnflow/columnar_util.py
Labels: enhancement, priority-high

#263 Refactor call caches in TaskArrayFunctions.
  columnflow/columnar_util.py
Labels: enhancement, priority-medium

#349 Add empty selector
  analysis_templates/cms_minimal/__cf_module_name__/config/analysis___cf_short_name_lc__.py
  analysis_templates/cms_minimal/law.cfg
  columnflow/selection/empty.py
  columnflow/tasks/histograms.py
  columnflow/tasks/selection.py
  law.cfg
Labels: enhancement, priority-medium

#346 running Producer in cf.PrepareMLEvents
  columnflow/ml/__init__.py
  columnflow/tasks/ml.py
Labels: enhancement, priority-low

#356 Feature/improve the docs
  columnflow/tasks/framework/base.py
  columnflow/tasks/framework/mixins.py
  columnflow/util.py
  docs/api/ml/index.rst
  docs/api/tasks/framework/decorators.rst
  docs/api/tasks/framework/index.rst
  docs/conf.py
  docs/law.cfg
Labels: documentation, priority-high, fix

#293 Feature/docs best pratices
  columnflow/calibration/cms/jets_coffea.py
  docs/index.rst
  docs/practices.md
  docs/user_guide/best_practices.md
  docs/user_guide/building_blocks/calibrators.md
  docs/user_guide/building_blocks/categories.md
  docs/user_guide/building_blocks/config_objects.md
  docs/user_guide/building_blocks/index.rst
  docs/user_guide/building_blocks/producers.md
  docs/user_guide/building_blocks/selectors.md
  docs/user_guide/cms_specializations.md
  docs/user_guide/debugging.md
  docs/user_guide/examples.md
  docs/user_guide/index.rst
  docs/user_guide/law.md
  docs/user_guide/ml.md
  docs/user_guide/plotting.md
  docs/user_guide/special_usecases.md
  docs/user_guide/structure.md
Labels: documentation, priority-medium
