Repository columnflow/columnflow, pull requests merged in 2023-01, with the labels that each got.

#137 Labels and Whitespace
  columnflow/plotting/example.py
  columnflow/plotting/plot2d.py
  columnflow/plotting/plot_util.py
  columnflow/tasks/cutflow.py
  columnflow/tasks/framework/plotting.py
  columnflow/tasks/plotting.py
Labels: low-priority, plotting

#141 Add hook to ml models for adding requirements.
  columnflow/ml/__init__.py
  columnflow/tasks/ml.py
Labels: enhancement, medium-priority

#116 Add scale and pdf weights producer
  columnflow/production/pdf.py
  columnflow/production/scale.py
Labels: enhancement, high-priority

#151 Share prepared ML events between ML models.
  columnflow/ml/__init__.py
  columnflow/tasks/framework/mixins.py
  columnflow/tasks/ml.py
  sandboxes/ml_tf.txt
Labels: enhancement, high-priority

#148 Move cms related array functions and tasks to cms/ subdirectories.
  columnflow/calibration/cms/__init__.py
  columnflow/calibration/cms/jets.py
  columnflow/calibration/cms/jets_coffea.py
  columnflow/calibration/cms/met.py
  columnflow/inference/cms/__init__.py
  columnflow/inference/cms/datacard.py
  columnflow/production/cms/__init__.py
  columnflow/production/cms/btag.py
  columnflow/production/cms/electron.py
  columnflow/production/cms/gen_top_decay.py
  columnflow/production/cms/mc_weight.py
  columnflow/production/cms/muon.py
  columnflow/production/cms/pdf.py
  columnflow/production/cms/pileup.py
  columnflow/production/cms/scale.py
  columnflow/production/cms/seeds.py
  columnflow/production/example.py
  columnflow/selection/example.py
  columnflow/tasks/cms/__init__.py
  columnflow/tasks/cms/external.py
  columnflow/tasks/cms/inference.py
  columnflow/tasks/external.py
  law.cfg
Labels: enhancement, medium-priority
