Repository columnflow/columnflow, pull requests merged in 2023-10, with the labels that each got.

#302 Configure filling of empty bins in inference model.
  columnflow/inference/__init__.py
  columnflow/inference/cms/datacard.py
Labels: enhancement, priority-medium

#303 Added MergeMLEvaluation task
  columnflow/tasks/ml.py
Labels: enhancement, priority-medium, ml

#281 Fix/nan pdf weights
  columnflow/production/cms/pdf.py
Labels: priority-medium, fix

#310 Allow writing root files in UniteColumns.
  columnflow/columnar_util.py
  columnflow/tasks/union.py
Labels: enhancement, priority-medium

#313 Enhance cmssw sandboxes
  columnflow/tasks/framework/remote.py
  sandboxes/_setup_cmssw.sh
  sandboxes/cmssw_columnar.sh
Labels: enhancement, priority-medium

#312 Use ZSTD(1) as a default compression for all parquet files.
  columnflow/tasks/calibration.py
  columnflow/tasks/framework/base.py
  columnflow/tasks/framework/mixins.py
  columnflow/tasks/ml.py
  columnflow/tasks/production.py
  columnflow/tasks/reduction.py
  columnflow/tasks/selection.py
  columnflow/tasks/union.py
Labels: enhancement, priority-high

#314 allow merging of MultiSettingsParameters and implement tests
  columnflow/tasks/framework/parameters.py
  tests/run_tests
  tests/test_task_parameters.py
Labels: testing, priority-low

#274 Add utility scripts for inspecting/diff'ing CF outputs.
  bin/cf_diff
  bin/cf_diff.py
  bin/cf_inspect
  bin/cf_inspect.py
Labels: enhancement, priority-low

#329 Disable parquet dictionary encoding.
  columnflow/tasks/framework/base.py
Labels: enhancement, priority-high

#333 Update columnar software in venvs.
  docs/requirements.txt
  sandboxes/columnar.txt
  sandboxes/ml_tf.txt
  setup.py
Labels: enhancement, priority-medium, sandboxes

#335 Fix root file export in UniteColumns.
  columnflow/columnar_util.py
  columnflow/tasks/union.py
Labels: priority-medium, fix
