Repository columnflow/columnflow, pull requests merged in 2023-04, with the labels that each got.

#227 Allow ML trainings to use data from multiple configs
  analysis_templates/cms_minimal/__cf_module_name__/ml/example.py
  columnflow/ml/__init__.py
  columnflow/tasks/framework/base.py
  columnflow/tasks/framework/mixins.py
  columnflow/tasks/framework/remote.py
  columnflow/tasks/ml.py
  columnflow/util.py
Labels: enhancement, high-priority

#221 enabled handling of just eight LHEScaleWeights
  columnflow/production/cms/scale.py
Labels: high-priority, fix

#224 change task outputs to dictionaries for calibration/selection/reduction
  analysis_templates/cms_minimal/__cf_module_name__/ml/example.py
  columnflow/production/normalization.py
  columnflow/tasks/calibration.py
  columnflow/tasks/cms/inference.py
  columnflow/tasks/cutflow.py
  columnflow/tasks/histograms.py
  columnflow/tasks/ml.py
  columnflow/tasks/plotting.py
  columnflow/tasks/production.py
  columnflow/tasks/reduction.py
  columnflow/tasks/selection.py
  columnflow/tasks/union.py
  columnflow/tasks/yields.py
Labels: enhancement, medium-priority

#232 Class aware decorators for task array functions
  columnflow/calibration/__init__.py
  columnflow/production/__init__.py
  columnflow/production/cms/scale.py
  columnflow/selection/__init__.py
Labels: enhancement, priority-medium
