Repository columnflow/columnflow, pull requests merged in 2023-02, with the labels that each got.

#157 Use mc_only switches in producers / calibrators.
  columnflow/calibration/cms/jets.py
  columnflow/calibration/cms/jets_coffea.py
  columnflow/production/cms/btag.py
  columnflow/production/cms/electron.py
  columnflow/production/cms/mc_weight.py
  columnflow/production/cms/muon.py
  columnflow/production/cms/pdf.py
  columnflow/production/cms/pileup.py
  columnflow/production/cms/scale.py
  columnflow/production/normalization.py
  sandboxes/columnar.txt
  sandboxes/ml_tf.txt
Labels: enhancement, medium-priority

#159 Add first draft for config_utils.
  analysis_templates/cms_minimal/__cf_module_name__/config/analysis___cf_short_name_lc__.py
  columnflow/config_util.py
  columnflow/util.py
Labels: enhancement, medium-priority

#162 Handling of empty chunks
  README.md
  columnflow/columnar_util.py
  columnflow/tasks/framework/mixins.py
  columnflow/tasks/histograms.py
  columnflow/tasks/production.py
  columnflow/tasks/selection.py
Labels: enhancement, high-priority

#180 Fix shift resolution.
  columnflow/tasks/cutflow.py
  columnflow/tasks/external.py
  columnflow/tasks/framework/base.py
  columnflow/tasks/framework/mixins.py
  columnflow/tasks/framework/plotting.py
  columnflow/tasks/framework/remote.py
  columnflow/tasks/histograms.py
  columnflow/tasks/ml.py
  columnflow/tasks/plotting.py
  columnflow/tasks/production.py
  columnflow/tasks/reduction.py
  columnflow/tasks/selection.py
Labels: high-priority, fix

#183 Remove need for multiple alias dicts per shift.
  analysis_templates/cms_minimal/__cf_module_name__/config/analysis___cf_short_name_lc__.py
  columnflow/columnar_util.py
  columnflow/config_util.py
  columnflow/tasks/reduction.py
  columnflow/tasks/selection.py
  tests/test_columnar_util.py
Labels: enhancement, medium-priority

#184 Modernize docs.
  README.md
  columnflow/__version__.py
  columnflow/columnar_util.py
  docs/_static/styles_sphinx_book_theme.css
  docs/conf.py
  docs/index.rst
  docs/requirements.txt
Labels: documentation, medium-priority

#186 Add config_util to create combinations of categories.
  columnflow/config_util.py
Labels: enhancement, low-priority

#187 Make plot tasks resolve categories after initializing dependent TaskArrayFunctions.
  columnflow/tasks/cutflow.py
Labels: high-priority, fix

#190 Fix process scale factor for plotting.
  columnflow/plotting/plot_util.py
Labels: fix, plotting

#188 Support hiding error bars for unstacked processes.
  columnflow/plotting/plot_functions_1d.py
  columnflow/plotting/plot_util.py
  columnflow/tasks/framework/plotting.py
Labels: medium-priority, plotting

#194 Handle lists of category selections in category_id producer.
  columnflow/config_util.py
  columnflow/production/categories.py
Labels: enhancement, medium-priority

#191 Fix order of array function dependency generation.
  columnflow/columnar_util.py
Labels: high-priority, fix

#198 New selector for applying data certification filter (golden JSON).
  columnflow/selection/cms/__init__.py
  columnflow/selection/cms/json_filter.py
Labels: enhancement, medium-priority

#199 New selector for applying MET filters.
  columnflow/selection/cms/met_filters.py
Labels: enhancement, medium-priority
