Repository columnflow/columnflow, pull requests merged in 2024-02, with the labels that each got.

#368 Documentation on the parameters for the Config Object
  analysis_templates/cms_minimal/__cf_module_name__/config/analysis___cf_short_name_lc__.py
  columnflow/config_util.py
  docs/api/categorization/index.rst
  docs/api/columnar_util.rst
  docs/api/config_util.rst
  docs/api/index.rst
  docs/api/production/cms.rst
  docs/api/production/index.rst
  docs/api/production/muon.rst
  docs/conf.py
  docs/user_guide/building_blocks/categories.md
  docs/user_guide/building_blocks/config_objects.md
  docs/user_guide/building_blocks/producers.md
  docs/user_guide/building_blocks/selectors.md
  docs/user_guide/law.md
  docs/user_guide/structure.md
Labels: documentation, priority-high

#392 Categorization guide
  docs/user_guide/building_blocks/categories.md
Labels: documentation, priority-medium

#393 implement pu_weight producer using correctionlib
  columnflow/production/cms/pileup.py
Labels: enhancement, priority-medium

#396 updates to the CreateYieldTable task
  columnflow/tasks/yields.py
Labels: enhancement, priority-low
