Repository columnflow/columnflow, pull requests merged in 2024-07, with the labels that each got.

#468 allow stitching in normalization_weights Producer
  columnflow/production/normalization.py
Labels: enhancement, priority-medium

#485 Make el9 the default on NAF.
  columnflow/tasks/framework/remote.py
  columnflow/tasks/framework/remote_bootstrap.sh
  law.cfg
Labels: enhancement, priority-medium

#487 Feature: added a stack option for the scaling
  columnflow/plotting/plot_util.py
Labels: enhancement, plotting

#486 Add btag sf config, allowing for additional corrector args.
  columnflow/production/cms/btag.py
Labels: enhancement, priority-high

#488 Route brace expansion
  analysis_templates/cms_minimal/__cf_module_name__/config/analysis___cf_short_name_lc__.py
  columnflow/columnar_util.py
  columnflow/tasks/framework/base.py
  columnflow/tasks/reduction.py
  columnflow/tasks/selection.py
  columnflow/tasks/union.py
Labels: enhancement, priority-high

#489 FIX `stack` argument for the scaling of processes in the plotting
  columnflow/plotting/plot_util.py
Labels: fix, plotting

#492 Raise exception on missing cross sections in normalization weight producer
  columnflow/production/normalization.py
Labels: enhancement, priority-medium

#490 Plotting updates
  columnflow/plotting/plot_all.py
  columnflow/plotting/plot_util.py
  columnflow/tasks/framework/plotting.py
  setup.sh
Labels: enhancement, priority-medium

#493 Configurable IO settings.
  columnflow/categorization/__init__.py
  columnflow/columnar_util.py
  columnflow/tasks/calibration.py
  columnflow/tasks/framework/mixins.py
  columnflow/tasks/histograms.py
  columnflow/tasks/production.py
  columnflow/tasks/selection.py
Labels: enhancement, priority-medium

#495 Scoped CSP requirements and inputs.
  columnflow/columnar_util.py
  columnflow/production/normalization.py
  columnflow/tasks/calibration.py
  columnflow/tasks/histograms.py
  columnflow/tasks/production.py
  columnflow/tasks/selection.py
Labels: enhancement, priority-medium

#496 Fix ProvideReducedEvents
  columnflow/tasks/framework/base.py
  columnflow/tasks/reduction.py
Labels: enhancement, priority-high

#497 Collect CSP sandbox through dependencies.
  columnflow/columnar_util.py
  columnflow/tasks/framework/mixins.py
Labels: enhancement, priority-medium

#499 add Selector for jet veto maps
  columnflow/selection/cms/jets.py
Labels: enhancement, priority-high

#501 Fix selector steps default resolution.
  columnflow/tasks/framework/base.py
  columnflow/tasks/framework/mixins.py
Labels: priority-medium, fix

#500 Fix and streamline jet veto maps selection.
  columnflow/selection/cms/jets.py
Labels: priority-high, fix

#505 Add TEC calibrator.
  analysis_templates/cms_minimal/law.cfg
  columnflow/calibration/cms/tau.py
Labels: enhancement, priority-medium

#506 Fix input lfn localization in ReduceEvents
  columnflow/tasks/calibration.py
  columnflow/tasks/reduction.py
  columnflow/tasks/selection.py
Labels: priority-high, fix

#508 Improve the way BRs are calculated for stitched datasets
  columnflow/production/normalization.py
Labels: enhancement

#507 allow customizing repr of CSPWs
  columnflow/columnar_util.py
  columnflow/tasks/framework/mixins.py
Labels: enhancement, priority-medium

#509 Expand docs with new features from PRs
  docs/user_guide/best_practices.md
  docs/user_guide/debugging.md
  docs/user_guide/ml.md
  docs/user_guide/plotting.md
  docs/user_guide/special_usecases.md
Labels: documentation, priority-medium

#510 Fix stitched normalization producer
  columnflow/production/normalization.py
Labels: bug, priority-high

#513 Accept multiple hist hooks.
  columnflow/tasks/framework/mixins.py
  columnflow/tasks/plotting.py
Labels: enhancement, priority-medium

#514 clamp eta values to 5.19 and add logger warnings
  columnflow/selection/cms/jets.py
Labels: priority-medium, fix

#512 Add CSPs to lookup keys for versions and locations.
  columnflow/tasks/framework/mixins.py
  docs/user_guide/best_practices.md
Labels: enhancement, priority-medium

#511 Fix hist and plot requirements.
  columnflow/tasks/histograms.py
  columnflow/tasks/plotting.py
Labels: priority-medium, fix

#515 Feature: Added the possibility to blind data points
  analysis_templates/cms_minimal/__cf_module_name__/config/analysis___cf_short_name_lc__.py
  columnflow/plotting/plot_functions_1d.py
  columnflow/plotting/plot_util.py
  columnflow/tasks/framework/plotting.py
Labels: enhancement, priority-medium, plotting

#519 added feature to skip categories by custom function
  columnflow/production/categories.py
Labels: enhancement, priority-low

#518 allow stitching using non-leaf processes in sum_mc_weight_per_process
  columnflow/production/normalization.py
Labels: fix
