Repository columnflow/columnflow, pull requests merged in 2024-12, with the labels that each got.

#579 Integrate chapter about systematic uncertainties into docs
  analysis_templates/cms_minimal/__cf_module_name__/config/analysis___cf_short_name_lc__.py
  analysis_templates/cms_minimal/__cf_module_name__/selection/example.py
  columnflow/columnar_util.py
  docs/api/index.rst
  docs/api/weights/all_weights.rst
  docs/api/weights/empty.rst
  docs/api/weights/index.rst
  docs/user_guide/building_blocks/config_objects.md
  docs/user_guide/index.rst
  docs/user_guide/shifts.md
Labels: documentation, enhancement, priority-medium

#577 Adapt JEC/JER calibrators to work with user-defined jet collections.
  columnflow/calibration/cms/jets.py
Labels: enhancement, priority-high, CMS

#527 Add `strict` option to `find_config_objects`.
  columnflow/tasks/framework/base.py
  columnflow/tasks/framework/mixins.py
Labels: enhancement, priority-medium

#581 Make input columns for deterministic seeds configurable.
  columnflow/production/cms/seeds.py
Labels: enhancement, priority-medium, CMS

#556 Update muon and electron SF producers (backward compatible)
  columnflow/production/cms/btag.py
  columnflow/production/cms/electron.py
  columnflow/production/cms/muon.py
Labels: enhancement, priority-medium

#588 Various smaller CMS run 3 changes
  columnflow/calibration/cms/jets.py
  columnflow/production/cms/btag.py
  columnflow/production/cms/electron.py
  columnflow/production/cms/muon.py
  columnflow/selection/cms/jets.py
Labels: enhancement, priority-medium

#590 Control workflow resources via law.cfg
  analysis_templates/cms_minimal/law.cfg
  columnflow/tasks/cms/base.py
  columnflow/tasks/framework/base.py
  columnflow/tasks/framework/remote.py
  law.cfg
Labels: enhancement, priority-medium

#592 Add producer for recalculating softdrop mass
  analysis_templates/cms_minimal/law.cfg
  columnflow/production/cms/jet.py
Labels: enhancement, priority-medium, CMS
