Repository columnflow/columnflow, pull requests merged in 2024-05, with the labels that each got.

#347 Add named event weight sets.
  analysis_templates/cms_minimal/__cf_module_name__/config/analysis___cf_short_name_lc__.py
  analysis_templates/cms_minimal/__cf_module_name__/weight/__init__.py
  analysis_templates/cms_minimal/__cf_module_name__/weight/example.py
  columnflow/__init__.py
  columnflow/tasks/framework/base.py
  columnflow/tasks/framework/mixins.py
  columnflow/tasks/histograms.py
  columnflow/tasks/ml.py
  columnflow/tasks/plotting.py
  columnflow/weight/__init__.py
  columnflow/weight/all_weights.py
  columnflow/weight/empty.py
  law.cfg
Labels: enhancement, priority-medium

#424 Make `categorizer_map` regular `dict` to prevent silent `KeyErrors`.
  columnflow/production/categories.py
Labels: priority-medium, fix

#426 multiply cferr columns with nominal btag weight
  columnflow/production/cms/btag.py
Labels: priority-high, fix

#422 add producers parameter to ProduceColumnsWrapper
  columnflow/tasks/production.py
Labels: enhancement, priority-low

#431 customize muon_weights output column names
  columnflow/production/cms/muon.py
Labels: enhancement, priority-high

#419 Feature/slice histograms
  columnflow/plotting/plot_util.py
  columnflow/tasks/framework/parameters.py
  columnflow/util.py
  tests/test_task_parameters.py
  tests/test_util.py
Labels: priority-low, plotting

#381 Added `Writing new tasks` and `Custom law.cfg file` section to docs
  columnflow/util.py
  docs/plots/user_guide/cf_plot.svg
  docs/user_guide/examples.md
Labels: documentation

#434 add ml_model_settings parameter
  columnflow/ml/__init__.py
  columnflow/tasks/framework/mixins.py
Labels: enhancement, ml

#407 add plot_profile function
  columnflow/plotting/plot_all.py
  columnflow/plotting/plot_functions_1d.py
  columnflow/plotting/plot_util.py
Labels: priority-low, plotting
