Repository columnflow/columnflow, pull requests merged in 2024-06, with the labels that each got.

#388 Refactor dynamic requirements of reduced events.
  columnflow/tasks/framework/base.py
  columnflow/tasks/histograms.py
  columnflow/tasks/ml.py
  columnflow/tasks/production.py
  columnflow/tasks/reduction.py
  columnflow/tasks/union.py
Labels: enhancement, priority-high

#416 add overflow and underflow variable setting
  columnflow/plotting/plot_util.py
  tests/test_plotting.py
Labels: priority-low, plotting

#446 Trigger skip function creation in derived CSP subclasses.
  columnflow/calibration/__init__.py
  columnflow/production/__init__.py
  columnflow/selection/__init__.py
  columnflow/util.py
  columnflow/weight/__init__.py
Labels: priority-high, fix

#448 Option to remove reduced events after merging.
  analysis_templates/cms_minimal/law.cfg
  columnflow/tasks/reduction.py
  law.cfg
Labels: enhancement, priority-medium

#449 Refactor pinning of output versions and locations.
  analysis_templates/cms_minimal/__cf_module_name__/config/analysis___cf_short_name_lc__.py
  analysis_templates/cms_minimal/law.cfg
  columnflow/tasks/framework/base.py
  docs/user_guide/best_practices.md
  law.cfg
Labels: enhancement, priority-high

#450 Documentation
  columnflow/util.py
  docs/plots/user_guide/cf_plot.svg
  docs/user_guide/examples.md
  docs/user_guide/examples/ml_code.py
Labels: documentation, priority-low

#451 Add hooks to modify store parts on a per-task level.
  analysis_templates/cms_minimal/__cf_module_name__/config/analysis___cf_short_name_lc__.py
  analysis_templates/cms_minimal/law.cfg
  columnflow/tasks/framework/base.py
  law.cfg
Labels: enhancement, priority-medium

#455 Handle empty LHE scale and pdf weight columns.
  columnflow/production/cms/pdf.py
  columnflow/production/cms/scale.py
Labels: enhancement, priority-medium

#458 Allow columns to be skipped in 'keep_columns' definitions.
  analysis_templates/cms_minimal/__cf_module_name__/config/analysis___cf_short_name_lc__.py
  columnflow/columnar_util.py
  columnflow/tasks/reduction.py
  columnflow/tasks/selection.py
  columnflow/tasks/union.py
Labels: enhancement, priority-high

#460 correct bug in normalization setup when no cross section is available for a process
  columnflow/production/normalization.py
Labels: priority-medium, fix

#453 Add markdown linting to CI
  .github/workflows/lint_and_test.yaml
  .markdownlint
  docs/requirements.txt
  sandboxes/dev.txt
  tests/run_docs
Labels: documentation, enhancement, priority-medium

#459 Ml fix and add more doc-string for PlotMLEvents
  columnflow/tasks/ml.py
Labels: documentation, fix, ml

#461 Improve process settings handling.
  columnflow/plotting/plot_util.py
  columnflow/tasks/cutflow.py
  columnflow/tasks/plotting.py
  docs/user_guide/plotting.md
Labels: enhancement, priority-medium

#466 Fix histogram filling.
  columnflow/columnar_util.py
Labels: priority-high, fix

#473 sort objects when passing wildcards
  columnflow/tasks/framework/base.py
Labels: enhancement, priority-low

#474 .copy not defined for awkward arrays. Use ak.copy instead
  columnflow/columnar_util.py
Labels: priority-high, fix

#476 Linting the docs :)
  .markdownlint
  README.md
  analysis_templates/cms_minimal/README.md
  docs/api/plotting/index.rst
  docs/api/production/cms.rst
  docs/api/production/muon.rst
  docs/task_overview/introduction.md
  docs/task_overview/plotting.md
  docs/task_overview/plotting.rst
  docs/task_overview/plotting_tasks.md
  docs/user_guide/best_practices.md
  docs/user_guide/building_blocks/categories.md
  docs/user_guide/building_blocks/config_objects.md
  docs/user_guide/building_blocks/producers.md
  docs/user_guide/building_blocks/selectors.md
  docs/user_guide/cms_specializations.md
  docs/user_guide/debugging.md
  docs/user_guide/examples.md
  docs/user_guide/law.md
  docs/user_guide/ml.md
  docs/user_guide/plotting.md
  docs/user_guide/sandbox.md
  docs/user_guide/structure.md
  tests/run_coverage
  tests/run_docs
Labels: documentation, testing, priority-medium

#475 BUG: `tenacity` version 8.4.0 doesn't work
  sandboxes/cf.txt
Labels: fix, sandboxes

#470 Add mechanism to hook into histograms (e.g. for ABCD methods)
  analysis_templates/cms_minimal/__cf_module_name__/config/analysis___cf_short_name_lc__.py
  columnflow/tasks/cutflow.py
  columnflow/tasks/framework/mixins.py
  columnflow/tasks/framework/plotting.py
  columnflow/tasks/plotting.py
Labels: enhancement, priority-medium

#471 Make bin shifting optional.
  analysis_templates/cms_minimal/law.cfg
  columnflow/columnar_util.py
  columnflow/tasks/cutflow.py
  columnflow/tasks/framework/parameters.py
  columnflow/tasks/histograms.py
  law.cfg
Labels: enhancement, priority-medium, plotting

#480 Small fix for the `GetDatasetLFNs` task
  columnflow/tasks/external.py
Labels: fix
