Repository columnflow/columnflow, pull requests merged in 2024-01, with the labels that each got.

#377 tests for columnflow.util
  columnflow/plotting/plot_all.py
  columnflow/plotting/plot_util.py
  columnflow/tasks/framework/parameters.py
  columnflow/tasks/yields.py
  columnflow/util.py
  docs/api/util.rst
  tests/test_util.py
Labels: testing

#366 Merge Plotting guide into document_sprint branch
  analysis_templates/cms_minimal/__cf_module_name__/plotting/__init__
  analysis_templates/cms_minimal/__cf_module_name__/plotting/example.py
  columnflow/tasks/external.py
  columnflow/tasks/framework/plotting.py
  columnflow/tasks/plotting.py
  docs/api/plotting/index.rst
  docs/api/tasks/cutflow.rst
  docs/api/tasks/index.rst
  docs/api/tasks/plotting.rst
  docs/conf.py
  docs/index.rst
  docs/plots/cf.PlotCutflowVariables1D_tpl_config_analy__1__c3947accbb__plot__proc_st__cat_incl__var_cf_jet1_pt.pdf
  docs/plots/cf.PlotCutflowVariables1D_tpl_config_analy__1__c3947accbb__plot__proc_tt__cat_incl__var_cf_jet1_pt.pdf
  docs/plots/cf.PlotCutflowVariables1D_tpl_config_analy__1__d8a37d3da9__plot__step0_Initial__proc_2_a2211e799f__cat_incl__var_cf_jet1_pt.pdf
  docs/plots/cf.PlotCutflowVariables1D_tpl_config_analy__1__d8a37d3da9__plot__step1_jet__proc_2_a2211e799f__cat_incl__var_cf_jet1_pt.pdf
  docs/plots/cf.PlotCutflowVariables1D_tpl_config_analy__1__d8a37d3da9__plot__step2_muon__proc_2_a2211e799f__cat_incl__var_cf_jet1_pt.pdf
  docs/plots/cf.PlotCutflow_tpl_config_analy__1__12a17bf79c__cutflow__cat_2j.pdf
  docs/plots/cf.PlotCutflow_tpl_config_analy__1__12a17bf79c__cutflow__cat_incl.pdf
  docs/plots/cf.PlotShiftedVariables1D_tpl_config_analy__1__42b45aba89__plot__proc_2_a2211e799f__unc_mu__cat_incl__var_jet1_pt.pdf
  docs/plots/cf.PlotShiftedVariables1D_tpl_config_analy__1__42b45aba89__plot__proc_2_a2211e799f__unc_mu__cat_incl__var_n_jet.pdf
  docs/plots/cf.PlotVariables1D_tpl_config_analy__1__0191de868f__plot__proc_2_a2211e799f__cat_incl__var_jet1_pt__c1.pdf
  docs/plots/cf.PlotVariables1D_tpl_config_analy__1__0191de868f__plot__proc_2_a2211e799f__cat_incl__var_n_jet__c1.pdf
  docs/plots/cf.PlotVariables1D_tpl_config_analy__1__12dfac316a__plot__proc_3_7727a49dc2__cat_2j__var_n_jet.pdf
  docs/plots/cf.PlotVariables1D_tpl_config_analy__1__12dfac316a__plot__proc_3_7727a49dc2__cat_incl__var_n_jet.pdf
  docs/plots/cf.PlotVariables1D_tpl_config_analy__1__4601e8554b__plot__proc_3_7727a49dc2__cat_incl__var_n_jet.pdf
  docs/plots/cf.PlotVariables1D_tpl_config_analy__1__be60d3bca7__plot__proc_2_a2211e799f__cat_incl__var_jet1_pt__c3.pdf
  docs/plots/cf.PlotVariables1D_tpl_config_analy__1__be60d3bca7__plot__proc_2_a2211e799f__cat_incl__var_n_jet__c3.pdf
  docs/plots/cf.PlotVariables1D_tpl_config_analy__1__c80529af83__plot__proc_2_a2211e799f__cat_incl__var_jet1_pt__c2.pdf
  docs/plots/cf.PlotVariables1D_tpl_config_analy__1__c80529af83__plot__proc_2_a2211e799f__cat_incl__var_n_jet__c2.pdf
  docs/plots/cf.PlotVariables2D_tpl_config_analy__1__b27b994979__plot__proc_2_a2211e799f__cat_incl__var_jet1_pt-n_jet.pdf
  docs/plots/cf.PlotVariables2D_tpl_config_analy__1__b27b994979__plot__proc_2_a2211e799f__cat_incl__var_n_jet-jet1_pt.pdf
  docs/requirements.txt
  docs/task_overview/index.rst
  docs/task_overview/introduction.md
  docs/task_overview/plotting.md
  docs/task_overview/plotting.rst
  docs/user_guide/plotting.md
  docs/user_guide/structure.md
Labels: documentation, priority-high

#372 Documentation about the usage of Machine Learning
  columnflow/ml/__init__.py
  docs/user_guide/examples/ml_code.py
  docs/user_guide/index.rst
  docs/user_guide/ml.md
  docs/user_guide/sandbox.md
Labels: documentation, priority-medium, ml
