Repository columnflow/columnflow, pull requests merged in 2024-11, with the labels that each got.

#558 Small fixes for weight calculation and stitching
  columnflow/production/normalization.py
  columnflow/selection/stats.py
Labels: enhancement, fix

#571 Make merging tasks remote workflows.
  columnflow/tasks/reduction.py
  columnflow/tasks/selection.py
Labels: enhancement, priority-medium

#570 Add --htcondor-disk parameter.
  analysis_templates/cms_minimal/law.cfg
  columnflow/tasks/framework/base.py
  columnflow/tasks/framework/remote.py
  law.cfg
Labels: enhancement, priority-high

#574 do not remove anything from plotting work tree
  columnflow/tasks/plotting.py
Labels: priority-high, fix, plotting

#575 Add deterministic seeds to jer smearing application
  columnflow/calibration/cms/jets.py
  columnflow/production/cms/seeds.py
  columnflow/util.py
Labels: enhancement, priority-high
