Repository columnflow/columnflow, pull requests merged in 2024-08, with the labels that each got.

#526 Fix over/underflow handling for histograms
  analysis_templates/cms_minimal/law.cfg
  columnflow/plotting/plot_util.py
  law.cfg
Labels: priority-high, fix

#529 Check all collections for colorbars when setting norm.
  columnflow/plotting/plot_functions_2d.py
Labels: priority-low, fix, plotting

#528 Minor fixes for weight producers.
  columnflow/calibration/__init__.py
  columnflow/production/__init__.py
  columnflow/selection/__init__.py
  columnflow/tasks/histograms.py
  columnflow/weight/__init__.py
  columnflow/weight/empty.py
Labels: fix

#530 Fix naf condor bug
  columnflow/columnar_util.py
  columnflow/tasks/framework/remote.py
  columnflow/tasks/framework/remote_bootstrap.sh
Labels: priority-high, fix

#532 update cms private work label to newest recommentations
  columnflow/plotting/plot_util.py
Labels: plotting, CMS

#536 Exclude Over/Underflow bins in ROOT file when writing Datacards
  columnflow/inference/__init__.py
  columnflow/inference/cms/datacard.py
Labels: priority-medium, fix

#540 Round the value for Lumi for 2d Plots
  columnflow/plotting/plot_functions_2d.py
Labels: fix, plotting
