Repository columnflow/columnflow, pull requests merged in 2025-04, with the labels that each got.

#668 Make lumi in normalization weight producer configurable.
  columnflow/production/normalization.py
Labels: enhancement, priority-low

#667 Ensure some tasks are only run locally
  columnflow/tasks/framework/decorators.py
  columnflow/tasks/framework/remote.py
Labels: priority-high, fix

#669 Fix config lookup for taf classes mixins.
  columnflow/tasks/framework/base.py
  columnflow/tasks/framework/mixins.py
  columnflow/tasks/framework/remote.py
Labels: priority-medium, fix

#661 CMS jet id producer
  columnflow/production/cms/jet.py
Labels: priority-high, fix, CMS

#663 Allow subpaths in external files.
  columnflow/tasks/external.py
Labels: enhancement, priority-medium

#662 Eager taf teardown when call function fails.
  columnflow/tasks/calibration.py
  columnflow/tasks/framework/decorators.py
  columnflow/tasks/framework/mixins.py
  columnflow/tasks/histograms.py
  columnflow/tasks/ml.py
  columnflow/tasks/production.py
  columnflow/tasks/reduction.py
  columnflow/tasks/selection.py
Labels: priority-medium, fix

#622 adding dy weights producer
  columnflow/production/cms/dy.py
Labels: enhancement, priority-high, CMS

#673 fix PlotCutflow task and requirements
  columnflow/tasks/cutflow.py
  columnflow/tasks/selection.py
Labels: priority-high, fix, plotting

#674 Apply new recommendation for egamma calibration
  columnflow/calibration/cms/egamma.py
Labels: enhancement, priority-medium, CMS

#665 Fix to jer application on jec variations
  columnflow/calibration/cms/jets.py
  columnflow/calibration/util.py
Labels: priority-high, fix, CMS

#680 Rename histograming -> histogramming
  analysis_templates/cms_minimal/__cf_module_name__/histogramming/__init__.py
  analysis_templates/cms_minimal/__cf_module_name__/histogramming/example.py
  analysis_templates/cms_minimal/law.cfg
  columnflow/__init__.py
  columnflow/histogramming/__init__.py
  columnflow/histogramming/default.py
  columnflow/tasks/framework/mixins.py
  docs/api/histograming/default.rst
  docs/api/histograming/index.rst
  docs/api/histogramming/default.rst
  docs/api/histogramming/index.rst
  docs/api/index.rst
  docs/user_guide/02_03_transition.md
  docs/user_guide/plotting.md
  docs/user_guide/structure.md
  law.cfg
Labels: bug, priority-high
