Repository columnflow/columnflow, pull requests merged in 2025-01, with the labels that each got.

#597 Store all pdf weights in pdf_weights producer
  columnflow/columnar_util.py
  columnflow/production/cms/pdf.py
Labels: enhancement, priority-medium, CMS

#598 Prefer true / false over 1 / 0 in shell scripts.
  analysis_templates/cms_minimal/setup.sh
  columnflow/__init__.py
  columnflow/tasks/framework/remote_bootstrap.sh
  sandboxes/_setup_cmssw.sh
  sandboxes/_setup_venv.sh
  setup.sh
Labels: enhancement, priority-medium

#599 Remove forest merge interface.
  columnflow/tasks/reduction.py
  columnflow/tasks/selection.py
Labels: enhancement, priority-medium

#602 fix setup incompatibility with zsh
  setup.sh
Labels: fix

#603 fix padding when there are no genjets in a chunk
  columnflow/calibration/cms/jets.py
Labels: fix

#608 Option to skip selection hists
  analysis_templates/cms_minimal/law.cfg
  columnflow/tasks/selection.py
  law.cfg
Labels: enhancement, priority-medium

#607 Flip stack plot order.
  columnflow/plotting/plot_all.py
  columnflow/plotting/plot_functions_1d.py
  columnflow/plotting/plot_util.py
Labels: enhancement, priority-medium, plotting, CMS

#610 Energy calibrations for electrons and photons
  columnflow/calibration/cms/egamma.py
  columnflow/production/cms/seeds.py
  columnflow/production/cms/supercluster_eta.py
Labels: enhancement, priority-high, CMS

#614 Hotfix: properly forward and use `deps_kwargs`.
  columnflow/columnar_util.py
Labels: priority-high, fix
